# Generated by Django 4.2.1 on 2023-05-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_list_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List_User',
        ),
    ]
